# Generated by Django 3.1.1 on 2020-11-01 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('long_id', models.FloatField(max_length=200)),
                ('lat_id', models.FloatField(max_length=200)),
                ('region', models.CharField(max_length=60)),
                ('town', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ItsmIncidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=50)),
                ('inc_description', models.CharField(max_length=200)),
                ('inc_detail_description', models.TextField()),
                ('event_start_time', models.DateTimeField()),
                ('event_end_time', models.DateTimeField(blank=True, null=True)),
                ('platform_inc_number', models.CharField(max_length=50)),
                ('long_site_id', models.FloatField()),
                ('lat_side_id', models.FloatField()),
                ('network_element', models.CharField(max_length=100)),
                ('priority_incident', models.CharField(max_length=30)),
                ('final_solution', models.TextField(blank=True, null=True)),
                ('status_inc', models.CharField(max_length=40)),
                ('traffic_affected', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('platform_inc_number', 'status_inc'),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comments')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('moderation', models.BooleanField(default=False)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.itsmincidents', verbose_name='Incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
