# Generated by Django 3.1.1 on 2020-11-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsmincidents',
            name='name_region',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
